import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

/**
 * Represents a region in the system where users can make reservations.
 *
 * This entity is used to store information about different regions or areas
 * available for reservations, including their seating capacity and rules
 * regarding smoking and children.
 *
 * @export
 * @class Region
 */
@Entity()
export class Region {
  /**
   * The unique identifier for the region.
   *
   * This column is auto-generated by the database and serves as the primary key.
   *
   * @type {number}
   * @memberof Region
   */
  @PrimaryGeneratedColumn()
  id: number;

  /**
   * The name of the region.
   *
   * This column stores the name of the region, such as "Main Hall" or "Bar".
   *
   * @type {string}
   * @memberof Region
   */
  @Column()
  name: string;

  /**
   * The seating capacity of the region.
   *
   * This column represents the maximum number of seats available in the region.
   *
   * @type {number}
   * @memberof Region
   */
  @Column()
  seatingCapacity: number;

  /**
   * Indicates whether smoking is allowed in the region.
   *
   * This column specifies whether smoking is permitted in this region. Defaults to `false`.
   *
   * @type {boolean}
   * @memberof Region
   */
  @Column({ default: false })
  smokingAllowed: boolean;

  /**
   * Indicates whether children are allowed in the region.
   *
   * This column specifies whether children are permitted in this region. Defaults to `true`.
   *
   * @type {boolean}
   * @memberof Region
   */
  @Column({ default: true })
  childrenAllowed: boolean;
}
